version: '3.3'
services:
    wordpress:
        image: wordpress:${WORDPRESS_VERSION}-php${PHP_VERSION}-apache
        build:
            context: ./phpdocker/wordpress
            args: 
                - WORDPRESS_VERSION
                - PHP_VERSION
                - NODE_VERSION
        external_links:
            - 'tribe-mysql:mysql'
            - 'tribe-mail:mail'
        networks:
            - proxy
        restart: unless-stopped
        volumes:
            - ../../lerna.json:/var/www/html/lerna.json
            - ../../package.json:/var/www/html/package.json
            - ../../.nvmrc:/var/www/html/.nvmrc
        environment:
            VIRTUAL_HOST: plugins.tribe
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_NAME: plugins
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_CACHE', false);
                define('SCRIPT_DEBUG', true);

    webserver:
        image: 'nginx:stable-alpine'
        environment:
            - 'VIRTUAL_HOST=plugins.tribe,*.plugins.tribe'
        volumes:
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - proxy
        links: 
            - wordpress

networks:
    proxy:
        external:
            name: global_proxy
